handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=INFO
javax.jmdns.level=OFF
javax.jmdns.impl.level=OFF
javax.jmdns.impl.JmDNSImpl.level=OFF
javax.jmdns.impl.tasks.level=OFF
