name=OpenThread
version=3.3.10
author=Rodrigo Garcia | GitHub @SuGlider
maintainer=Rodrigo Garcia <Rodrigo.Garcia@espressif.com>
sentence=Library for OpenThread Network on ESP32.
paragraph=This library wraps the OpenThread stack for Arduino.
category=Communication
url=https://github.com/espressif/arduino-esp32/
architectures=esp32
