blank_issues_enabled: false
contact_links:
  - name: Arduino Core for Espressif Discord Server
    url: https://discord.gg/8xY6e9crwv
    about: Community Discord server for questions and help
  - name: ESP32 Forum - Arduino
    url: https://esp32.com/viewforum.php?f=19
    about: Official Forum for questions
