blank_issues_enabled: false
contact_links:
  - name: Arduino ESP32 Gitter Channel
    url: https://gitter.im/espressif/arduino-esp32
    about: Community channel for questions and help
  - name: ESP32 Forum - Arduino
    url: https://esp32.com/viewforum.php?f=19
    about: Official Forum for questions