name: Feature request
description: Suggest an idea for this project
labels: ["Type: Feature request"]
body:
  - type: markdown
    attributes:
      value: |
        * We welcome any ideas or feature requests! It is helpful if you can explain exactly why the feature would be useful.
        * There are usually some outstanding feature requests in the [existing issues list](https://github.com/espressif/arduino-esp32/issues?q=is%3Aopen+is%3Aissue+label%3A%22Type%3A+Feature+request%22), feel free to add comments to them.
        * If you would like to contribute, please read the [contributions guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html).
  - type: input
    id: Area
    attributes:
      label: Related area
      description: Please briefly explain the area of your Feature Request.
      placeholder: eg. Board support, specific Peripheral, BT, Wifi...
    validations:
      required: true
  - type: input
    id: HW
    attributes:
      label: Hardware specification
      description: Please provide if your proposal depends on specific Hardware.
      placeholder: eg. Support for ESP32 DevKitC, ESP32-C3 DevKitM...
    validations:
      required: true
  - type: textarea
    id: problem-related
    attributes:
      label: Is your feature request related to a problem?
      description: Please provide a clear and concise description of what the problem is. Add relevant issue link.
      placeholder: ex. I'm facing the issue/missing function...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: Please provide a clear and concise description of what you want to happen.
      placeholder: ex. When using this function...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Please provide a clear and concise description of any alternative solutions or features you've considered.
      placeholder: ex. Choosing other approach wouldn't work, because...
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Please add any other context or screenshots about the feature request here.
      placeholder: ex. This would work only when ...
  - type: checkboxes
    id: confirmation
    attributes:
      label: I have checked existing list of Feature requests and the Contribution Guide
      description: You agree to check all the resources above before opening a new Feature request.
      options:
        - label: I confirm I have checked existing list of Feature requests and Contribution Guide.
          required: true
