name=Hash
version=3.3.12
author=lucasssvaz
maintainer=lucasssvaz
sentence=Bundle of hashing functions for the ESP32
paragraph=This library provides hashing functions for sketches, including SHA-1/2/3, HMAC, and PBKDF2-HMAC.
category=Security
url=
architectures=esp32
