name=ESP_Video
version=3.3.10
author=Dong Heng
maintainer=Dong Heng <dongheng@espressif.com>
sentence=Library for ESP camera video capture
paragraph=Wraps esp_video for MIPI-CSI, DVP and V4L2 capture on supported SoCs.
category=Signal Input/Output
url=https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP_Video
architectures=esp32
includes=ESP_Video.h
