//Generated by mkmodel
#pragma once
#include <string.h>
#include "dl_lib_coefgetter_if.h"
#include "dl_lib_matrix.h"
#include "dl_lib_matrixq.h"

extern const model_coeff_getter_t get_coeff_nihaoxiaozhi_wn5;
