name: DangerJS Pull Request linter
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  pull-request-style-linter:
    runs-on: ubuntu-latest
    steps:
      - name: DangerJS pull request linter
        uses: espressif/shared-github-dangerjs@1a02c207e7000dbb2b4b0e6d9754f25c0b867241 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          instructions-cla-link: "https://cla-assistant.io/espressif/arduino-esp32"
          instructions-contributions-file: "docs/en/contributing.rst"
          rule-max-commits: "false"
          rule-target-branch: "false"
          commit-messages-min-summary-length: "10"
